spring.datasource.url=jdbc:postgresql://ep-weathered-fog-a5d3w2it-pooler.us-east-2.aws.neon.tech/snap-link?user=snap-link_owner&password=npg_q3DxAdvBeW2z&sslmode=require
spring.datasource.username=snap-link_owner
spring.datasource.password=npg_q3DxAdvBeW2z
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10


spring.redis.host=honest-imp-11083.upstash.io
spring.redis.port=6379
spring.redis.password=AStLAAIncDE0MTg5YzNmYTc4ODk0Mjc0OTQwM2Y0M2E2ZjRlY2ZiNHAxMTEwODM
spring.redis.ssl.enabled=true


jwt.secret=l1kJ7GgD9X0T1v3oQ4cB9sJmPzV8aN3yqFh2K+R7T6U=
jwt.expiration=172800000
jwt.access-token.expiration=9000000
jwt.refresh-token.expiration=259200000

logging.level.root=INFO
logging.level.com.url.shortener=DEBUG


frontend.url=http://localhost:5173/

# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=snaplink-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
